

POST http://localhost:3000/register/

Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}
###
POST http://localhost:3000/register/

Content-Type: application/json

{
    "username":"adam_richard"
}
####


POST http://localhost:3000/login/

Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

####

//API 3
GET http://localhost:3000/user/tweets/feed/

###
//api4
GET http://localhost:3000/user/following/

###
//api5
GET http://localhost:3000/user/followers/

###
//api6
GET http://localhost:3000/tweets/:tweetId/

###
//api7
GET http://localhost:3000/tweets/:tweetId/likes/


###
//api8
GET http://localhost:3000/tweets/:tweetId/replies/



###

//api9

GET http://localhost:3000/user/tweets/

###
//api10
POST  http://localhost:3000/user/tweets/

Content-Type: application/json

{
   "tweet": "The Mornings..."
}

###




//API11
DELETE http://localhost:3000/tweets/:tweetId/

###
